# Generated by Django 5.0.3 on 2024-05-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPlaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=150, null=True)),
                ('price', models.CharField(max_length=25, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yieldManagement.vendor')),
            ],
        ),
    ]
