# Generated by Django 5.0.3 on 2024-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='CheckIn',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
