# Generated by Django 5.0.3 on 2024-05-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yieldManagement', '0002_marketplacemodel_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacemodel',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
