# Generated by Django 5.0.3 on 2024-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldManagement', '0003_rename_vendor_marketplacemodel_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='hotelId',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
