# Generated by Django 5.0.3 on 2024-05-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldManagement', '0004_marketplacemodel_hotelid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlydate', models.CharField(max_length=25, null=True)),
                ('capacity', models.CharField(max_length=20, null=True)),
                ('occInd', models.CharField(max_length=25, null=True)),
                ('occGroup', models.CharField(max_length=25, null=True)),
                ('occAllotment', models.CharField(max_length=25, null=True)),
                ('occGroupTent', models.CharField(max_length=25, null=True)),
                ('occAllotmentTent', models.CharField(max_length=25, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalenderYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, null=True)),
                ('fromDate', models.CharField(max_length=20, null=True)),
                ('toDate', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlydate', models.CharField(max_length=25, null=True)),
                ('capacity', models.CharField(max_length=20, null=True)),
                ('occInd', models.CharField(max_length=25, null=True)),
                ('occGroup', models.CharField(max_length=25, null=True)),
                ('occAllotment', models.CharField(max_length=25, null=True)),
                ('occGroupTent', models.CharField(max_length=25, null=True)),
                ('occAllotmentTent', models.CharField(max_length=25, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.CharField(max_length=25, null=True)),
                ('toDate', models.CharField(max_length=25, null=True)),
                ('note', models.CharField(max_length=500, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OverRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.CharField(max_length=25, null=True)),
                ('toDate', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(max_length=25, null=True)),
                ('value', models.CharField(max_length=25, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(max_length=25, null=True)),
                ('period', models.CharField(max_length=25, null=True)),
                ('weekday', models.CharField(max_length=25, null=True)),
                ('dayMonth', models.CharField(max_length=25, null=True)),
                ('sendTo', models.CharField(max_length=25, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(default='NDD', max_length=25, null=True)),
                ('min_price', models.CharField(max_length=25, null=True)),
                ('max_price', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(max_length=25, null=True)),
                ('single', models.CharField(max_length=25, null=True)),
                ('double', models.CharField(max_length=25, null=True)),
                ('triple', models.CharField(max_length=25, null=True)),
                ('quad', models.CharField(max_length=25, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(default='All Years', max_length=50, null=True)),
                ('months', models.CharField(default='All', max_length=50, null=True)),
                ('weekdays', models.CharField(default='All', max_length=50, null=True)),
                ('days', models.CharField(default='1', max_length=10, null=True)),
                ('sold10', models.CharField(max_length=25, null=True)),
                ('sold15', models.CharField(max_length=25, null=True)),
                ('sold20', models.CharField(max_length=25, null=True)),
                ('sold40', models.CharField(max_length=25, null=True)),
                ('sold50', models.CharField(max_length=25, null=True)),
                ('sold60', models.CharField(max_length=25, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreShold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, null=True)),
                ('weekday', models.CharField(max_length=20, null=True)),
                ('min_price', models.CharField(max_length=20, null=True)),
                ('max_price', models.CharField(max_length=20, null=True)),
                ('sellout', models.CharField(max_length=20, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
