# Generated by Django 5.0.3 on 2024-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldManagement', '0005_budgetyield_calenderyield_forecastyield_noteyield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacemodel',
            old_name='CheckIn',
            new_name='CheckIn0',
        ),
        migrations.RenameField(
            model_name='marketplacemodel',
            old_name='price',
            new_name='CheckIn1',
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='CheckIn2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='CheckIn3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='CheckIn4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='CheckIn5',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='CheckIn6',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='locationId',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='review',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
