# Generated by Django 5.0.3 on 2024-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldManagement', '0006_rename_checkin_marketplacemodel_checkin0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day0', models.CharField(max_length=15, null=True)),
                ('day1', models.CharField(max_length=15, null=True)),
                ('day2', models.CharField(max_length=15, null=True)),
                ('day3', models.CharField(max_length=15, null=True)),
                ('day4', models.CharField(max_length=15, null=True)),
                ('day5', models.CharField(max_length=15, null=True)),
                ('day6', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
